name: Build and test

on:
  push:

jobs:
  test-and-build:
    runs-on: ubuntu-latest
#     defaults:
#       run:
#         working-directory: ./scripts
    steps:
      - name: Check out the repository
        uses: actions/checkout@v6
      - name: Install xmllint
        run: sudo apt -q install -y libxml2-utils
      - name: Validate mapping
        run: ./mapping/script/validate.sh
      - name: Validate facet configuration
        run: ./config/script/validate.sh
      - name: Set up JDK 21 for x64
        uses: actions/setup-java@v5
        with:
          java-version: '25'
          distribution: 'temurin'
          architecture: x64
      - name: Cache local Maven repository
        uses: actions/cache@v6
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Maven build Java project
        run: ./build.sh -B --settings .maven-settings.xml
      - name: Compile value maps
        run: ./value-maps/script/build.sh
            

# TRAVIS CONFIG
#            
#       script:
#        - ./build.sh -B --settings .maven-settings.xml
#        - value-maps/script/build.sh
# 
#       after_success:
#        - value-maps/script/push-changes.sh